[project]
name = 'Tokenized-Agriculture-Seed-Development-Networks'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.field-testing]
path = 'contracts/field-testing.clar'
clarity_version = 2
epoch = 2.5

[contracts.licensing-management]
path = 'contracts/licensing-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
